// import $ from 'jquery';
import 'acf/field-sweet-spot';
import 'acf/select-conditions';
import 'acf/condition-type-regex';
import 'acf/condition-type-object-type';
import 'acf/id-field';
import 'acf/post-object-message-template';
import 'acf/popup';
import 'acf/repeater-post-sync';
import 'acf/repeater-deny-sort';
import 'acf/select-nav-menu';
import 'acf/accordion-layout';
import 'acf/tab-url-navigation';
